# This file was generated by the agent-insights release workflow. DO NOT EDIT.
cask "agent-insights-cli" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "0e88a241a2578dd69daf90a2359fea195bcf0c708143fd66f779bf4db23231fe"
      url "https://github.com/tomnagengast/agent-insights/releases/download/v#{version}/agent-insights_#{version}_darwin_arm64.tar.gz"
    end

    on_intel do
      sha256 "ac34a618b63f57ced1d0061160038b7bcf466577170a4918c17e2c25696f2d0a"
      url "https://github.com/tomnagengast/agent-insights/releases/download/v#{version}/agent-insights_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "agent-insights-cli"
  desc "CLI for generating AI agent session insights reports."
  homepage "https://github.com/tomnagengast/agent-insights"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-insights"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-insights"]
    end
  end

  caveats <<~EOS
    Requires authenticated `claude` on PATH for facet and report generation.
  EOS
end
