# This file was generated by the agent-insights release workflow. DO NOT EDIT.
cask "agent-insights-cli" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "d9d8c4d583b7de12ab0782931fe87a762a6160244bccac9de4430d4ae58d5563"
      url "https://github.com/tomnagengast/agent-insights/releases/download/v#{version}/agent-insights_#{version}_darwin_arm64.tar.gz"
    end

    on_intel do
      sha256 "f31a3474f6f2f698195f7d918c31ab6d2d097873d0ebb020abfb2d95746c4c5b"
      url "https://github.com/tomnagengast/agent-insights/releases/download/v#{version}/agent-insights_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "agent-insights-cli"
  desc "CLI for generating AI agent session insights reports."
  homepage "https://github.com/tomnagengast/agent-insights"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-insights"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-insights"]
    end
  end

  caveats <<~EOS
    Requires authenticated `claude` on PATH for facet and report generation.
  EOS
end
