# This file was generated by the agent-insights release workflow. DO NOT EDIT.
cask "agent-insights-cli" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "639ccfa20584a48e3780df974da4379f76da97bef6cd0c4ec2b92fc596980731"
      url "https://github.com/tomnagengast/agent-insights/releases/download/v#{version}/agent-insights_#{version}_darwin_arm64.tar.gz"
    end

    on_intel do
      sha256 "63541a1edc791b34a533ac086c28aef86e3f1e908033784a617cda6c3a48b121"
      url "https://github.com/tomnagengast/agent-insights/releases/download/v#{version}/agent-insights_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "agent-insights-cli"
  desc "CLI for generating Claude Code session insights reports."
  homepage "https://github.com/tomnagengast/agent-insights"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-insights"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-insights"]
    end
  end

  caveats <<~EOS
    Requires authenticated `claude` on PATH for facet and report generation.
  EOS
end
