# This file was generated by GoReleaser. DO NOT EDIT.
cask "compactor-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "96c8547dbd29432abb685da4ae245b5c685b3652dc5460372ca377431c36e31d"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e69f2bf0c002e94de3d8dd12dbecc6eecb2b9613ab056bcad445037e7d0768b"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "965b2e96d11dbfbef09ce7ae814d0f002e3676c086ac1eacb4d54d2698307e2f"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "621e83f46662389fcc56e9cc693475b7cca21807d7c113d5e5e628d3211026a6"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "compactor-cli"
  desc "Progressive disclosure for agent compaction."
  homepage "https://github.com/tomnagengast/compactor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compactor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/compactor"]
    end
  end

  # No zap stanza required

end
