# This file was generated by GoReleaser. DO NOT EDIT.
cask "compactor-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "87f66d64bce9d7d51ce65df23a6e2af61e71f1623dd0693d9805215ae076f752"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb7af19bd5de8f515a6f5cf5ba2f0a807e1249e873ec1c6767284c0449e3b95f"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "04c4e2ae2af23d156e6fc65044600c60853f2bd9d40677c112549c20d0737227"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9855449323b02c1eba5bf0bf138be6792c1cab0987c0c8900f8ce05ee58ceff"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "compactor-cli"
  desc "Progressive disclosure for agent compaction."
  homepage "https://github.com/tomnagengast/compactor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compactor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/compactor"]
    end
  end

  # No zap stanza required

end
