# This file was generated by GoReleaser. DO NOT EDIT.
cask "compactor-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "7f9c2eeff50a430c0abb7fec3e1de85aba8f6e82030b1065649673b1efbd2300"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b2b80e0ca9125a11a8b4ffabe49ba6b8b5edf25edc9d66b77c0760372effff8"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25e0c6a33fa90d73477cb71c9489e4c185092a94bc55343682d7a291bd8cbde5"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "356dd63e134da7e86f9ceaa6c2bdc1bc14df2fa6268c14aebfdd433386374c8f"
      url "https://github.com/tomnagengast/compactor/releases/download/v#{version}/compactor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "compactor-cli"
  desc "Progressive disclosure for agent compaction."
  homepage "https://github.com/tomnagengast/compactor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compactor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/compactor"]
    end
  end

  # No zap stanza required

end
