# This file was generated by GoReleaser. DO NOT EDIT.
cask "memoryd-cli" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "533db265b9174eb04ad9c7966a8174482a980dd28aa2225b344adc098588d6e0"
      url "https://github.com/tomnagengast/agent-memoryd/releases/download/v#{version}/agent-memoryd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "memoryd-cli"
  desc "Local memory daemon and MCP server for coding agents."
  homepage "https://github.com/tomnagengast/agent-memoryd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memoryd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memoryd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `memoryd init` after installation to create config, Git hooks, and the managed daemon service.
  EOS
end
