# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "b1034700b9f79cf8b2abff3d5f344beed0365ce603063599807a37c1d1a0c3b8"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "513311d85dde2c28e2ad2b0dbebb948aa43bbcadbca98d22292705202a12b028"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e74eed2c63641b76f5ed6badd2acd03cca6dc08c8b63fd591b3646d025ff9d1"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66aad1a42e30e5e838d7f1d13f074f46bfa9c01817e526ed493c806f8cae696d"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scout-cli"
  desc "Reconnaissance for your context window."
  homepage "https://github.com/tomnagengast/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
