# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout-cli" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "b641f4f012526f5abaea963c2f21f7ba767725a71f7bf799db9d79e49c8ded76"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e6916e21aeda9104998fc46c1a9f3e4e7c4f42fb5624f0339afd6c27d1beac5"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52b70d195df15fb57939c469927943aa31f95b44aa2f339429c3d68136944c57"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d871adeb55a4954a5d4def40a042d0038511de9bf698cb59fed682b4abdcf92"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scout-cli"
  desc "Reconnaissance for your context window."
  homepage "https://github.com/tomnagengast/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
