# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "5e837af51c6fe0d0f4450b1bc424691e60e02464f474b05a6595b930fc7b6659"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ff39a6bd815e472a634065447c0e1c638c1fb9cbf5367bf4be22ce639072d26"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b34ab7155311a55c9c86a4f674e8a96491ff5f0b54ef5fd71202f2614f95ffb"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3acd3648a5232785cddef4b8eb1eacc805973266ce8074954514775f0dae299"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scout"
  desc "Reconnaissance for your context window."
  homepage "https://github.com/tomnagengast/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
