# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a9e1b23b04ddad8b8f827db64e9f530759338b41bee88d3a4ba8139878ee0e58"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "719750ce4e9f214006c329164a42fbb43a70e99bc8c779d6003b0a69c14abadf"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a9be8d62bf711117d2edb1d23544aba638a4d86a044c4f3b6f38305c0fe9987"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3b2b96936114973e05ee6652eda126e62ba2864d8b8579704e5d43c5455f903"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scout"
  desc "Reconnaissance for your context window."
  homepage "https://github.com/tomnagengast/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
