# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout-cli" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "327613420475ef22f83e2b49ab2dbd294337b7cea5ca1d3a915a375b930394a8"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "513db9b2f32bc9ef91dbd832afdd04036626fefbe47f61e8d017d3e206d9a652"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d03d5cb79d62c13aafec6a6b8483d62b15bf2a33c6d0e4fbdfaad1f41a7f5bb"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "93b14c8253289148eb293ab9e1bee03833f8d10729387f4a9e66a4b6ab416431"
      url "https://github.com/tomnagengast/scout/releases/download/v#{version}/scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scout-cli"
  desc "Reconnaissance for your context window."
  homepage "https://github.com/tomnagengast/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
