# This file is generated by the workflow release pipeline. DO NOT EDIT.
cask "workflow-cli" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "8b04b4dd9b82bf26bfb7805dbd1172ad3866170450110cff930495a1387a1158"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad31fca5b4e9590a06150c54c992090fd0b8652b04236321c17d58cf197ecd08"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c76a3d930646f43271597b6cbb1cbae803d3d4531a96d8b274c816f7e61bef7c"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "652527bc1a53fa4340dca73a9066d453abafb74abc7fb24c4ce1cfd5e3e9a249"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "workflow-cli"
  desc "Standalone runner for Claude Code dynamic workflow scripts"
  homepage "https://github.com/tomnagengast/workflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workflow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/workflow"]
    end
  end
end
