# This file is generated by the workflow release pipeline. DO NOT EDIT.
cask "workflow-cli" do
  version "0.0.7"

  on_macos do
    on_intel do
      sha256 "01fb3630395e81e7d292c7c62282bd9f8cf9000f89b6dfaad44b255202466bb2"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "08eebeb582d6e82ce9c38ca6828cb88385188c4d84a5baddedd14a8b1e5fb562"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "08d9600dfcf43983d7bce1948e7b1ac479347c653be6ba74253a36ded842991b"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "25673cf8bd339973e4c11a41d8b555cc42cd2cbf898a8ef4d25004e34b6202a3"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "workflow-cli"
  desc "Standalone runner for Claude Code dynamic workflow scripts"
  homepage "https://github.com/tomnagengast/workflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workflow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/workflow"]
    end
  end
end
