# This file is generated by the workflow release pipeline. DO NOT EDIT.
cask "workflow-cli" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "e568352873fec9673830099dba713acb236ce1f23505f7b6fe3f7eec82b62390"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98c683a963a146d74a96e2927fe0e20d846baba82793fe3541cb03ab641055fb"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fd0a768597c5fca3aed164b2b20a1b7cce800e4357feecf60b9670e7c97ed6b"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c4b780bb8ed4ca8d3d9124def3215357799c45af3d2d1df70d75a1f52d97c803"
      url "https://github.com/tomnagengast/workflow/releases/download/v#{version}/workflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "workflow-cli"
  desc "Standalone runner for Claude Code dynamic workflow scripts"
  homepage "https://github.com/tomnagengast/workflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workflow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/workflow"]
    end
  end
end
